import type { SpectrumBlock } from "../@types";

const data: SpectrumBlock[] = [
  {
    owner: "A1",
    ownerLongName: "A1 Bulgaria",
    startFreq: 925.1,
    endFreq: 926.9,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 880.1,
      endFreq: 881.9,
    },
    arfcns: "ARFCNs 975-983",
  },
  {
    owner: "?",
    ownerLongName: "Unallocated",
    startFreq: 926.9,
    endFreq: 927.1,
    type: "genericPaired",
    pairedWith: {
      type: "genericPaired",
      startFreq: 881.9,
      endFreq: 882.1,
    },
  },
  {
    owner: "Yettel",
    ownerLongName: "Yettel Bulgaria",
    startFreq: 927.1,
    endFreq: 928.9,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 882.1,
      endFreq: 883.9,
    },
    arfcns: "ARFCNs 985-993",
  },
  {
    owner: "?",
    ownerLongName: "Unallocated",
    startFreq: 928.9,
    endFreq: 929.1,
    type: "genericPaired",
    pairedWith: {
      type: "genericPaired",
      startFreq: 883.9,
      endFreq: 884.1,
    },
  },
  {
    owner: "Vivacom",
    ownerLongName: "Vivacom Bulgaria",
    startFreq: 929.1,
    endFreq: 934.1,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 884.1,
      endFreq: 889.1,
    },
    earfcns: [3516],
    details: "Nationwide B8 LTE deployment",
  },
  {
    owner: "Vivacom",
    ownerLongName: "Vivacom Bulgaria",
    startFreq: 934.1,
    endFreq: 938.7,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 889.1,
      endFreq: 893.7,
    },
    uarfcns: [2981],
    arfcns: [17],
  },
  {
    owner: "Vivacom",
    ownerLongName: "Vivacom Bulgaria",
    startFreq: 938.7,
    endFreq: 940.3,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 893.7,
      endFreq: 895.3,
    },
    arfcns: "ARFCNs 19-26",
  },
  {
    owner: "?",
    ownerLongName: "Unallocated",
    startFreq: 940.3,
    endFreq: 940.7,
    type: "genericPaired",
    pairedWith: {
      type: "genericPaired",
      startFreq: 895.3,
      endFreq: 895.7,
    },
  },
  {
    owner: "A1",
    ownerLongName: "A1 Bulgaria",
    startFreq: 940.7,
    endFreq: 945.5,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 895.7,
      endFreq: 900.5,
    },
    uarfcns: [3016],
  },
  {
    owner: "A1",
    ownerLongName: "A1 Bulgaria",
    startFreq: 945.5,
    endFreq: 950.1,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 900.5,
      endFreq: 905.1,
    },
    earfcns: [3678],
    details: [
      "Nationwide B8 LTE deployment",
      "Presents as 5 MHz but uses 23 resource blocks",
    ],
  },
  {
    owner: "?",
    ownerLongName: "Unallocated",
    startFreq: 950.1,
    endFreq: 950.5,
    type: "genericPaired",
    pairedWith: {
      type: "genericPaired",
      startFreq: 905.1,
      endFreq: 905.5,
    },
  },
  {
    owner: "Yettel",
    ownerLongName: "Yettel Bulgaria",
    startFreq: 950.5,
    endFreq: 955.5,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 905.5,
      endFreq: 910.5,
    },
    uarfcns: [3065],
    arfcns: [78],
  },
  {
    owner: "Yettel",
    ownerLongName: "Yettel Bulgaria",
    startFreq: 955.5,
    endFreq: 959.9,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 910.5,
      endFreq: 914.9,
    },
    earfcns: [3774, 3780],
    arfcns: "ARFCNs 103-124",
    details: [
      "LTE EARFCN 3780 - 3 MHz, EARFCN - 3774 5 MHz.",
      "The rest of the spectrum is used for 2G.",
    ],
  },
];

export default data;
