import type { SpectrumBlock } from "../@types";

const data: SpectrumBlock[] = [
  {
    owner: "A1",
    ownerLongName: "A1 Bulgaria",
    startFreq: 925.1,
    endFreq: 926.9,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 880.1,
      endFreq: 881.9,
    },
    arfcns: "ARFCNs 975-983",
  },
  {
    owner: "?",
    ownerLongName: "Unallocated",
    startFreq: 926.9,
    endFreq: 927.1,
    type: "genericPaired",
    pairedWith: {
      type: "genericPaired",
      startFreq: 881.9,
      endFreq: 882.1,
    },
  },
  {
    owner: "Yettel",
    ownerLongName: "Yettel Bulgaria",
    startFreq: 927.1,
    endFreq: 928.9,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 882.1,
      endFreq: 883.9,
    },
    arfcns: "ARFCNs 985-993",
  },
  {
    owner: "?",
    ownerLongName: "Unallocated",
    startFreq: 928.9,
    endFreq: 929.1,
    type: "genericPaired",
    pairedWith: {
      type: "genericPaired",
      startFreq: 883.9,
      endFreq: 884.1,
    },
  },
  {
    owner: "Vivacom",
    ownerLongName: "Vivacom Bulgaria",
    startFreq: 929.1,
    endFreq: 940.3,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 884.1,
      endFreq: 895.3,
    },
    earfcns: [3516],
    uarfcns: [2981],
    arfcns: [17, 19, 20, 21, 22, 23, 24, 25, 26],
    details: "Nationwide B8 LTE 5 MHz, B8 3G and B8 2G deployment",
  },
  {
    owner: "?",
    ownerLongName: "Unallocated",
    startFreq: 940.3,
    endFreq: 940.7,
    type: "genericPaired",
    pairedWith: {
      type: "genericPaired",
      startFreq: 895.3,
      endFreq: 895.7,
    },
  },
  {
    owner: "A1",
    ownerLongName: "A1 Bulgaria",
    startFreq: 940.7,
    endFreq: 950.1,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 895.7,
      endFreq: 905.1,
    },
    earfcns: [3654, 3678],
    uarfcns: [3016],
    details: [
      "Nationwide B8 LTE deployment",
      "B8 3G deployment in the process of being shut down",
      "LTE presents as 5 MHz but uses 23 resource blocks (4.6 MHz)",
      "LTE presents as 10 MHz but uses 47 resource blocks (9.4 MHz), only in areas without 3G",
    ],
  },
  {
    owner: "?",
    ownerLongName: "Unallocated",
    startFreq: 950.1,
    endFreq: 950.5,
    type: "genericPaired",
    pairedWith: {
      type: "genericPaired",
      startFreq: 905.1,
      endFreq: 905.5,
    },
  },
  {
    owner: "Yettel",
    ownerLongName: "Yettel Bulgaria",
    startFreq: 950.5,
    endFreq: 959.9,
    type: "fddDown",
    pairedWith: {
      type: "fddUp",
      startFreq: 905.5,
      endFreq: 914.9,
    },
    earfcns: [3780],
    uarfcns: [3065],
    arfcns: [78],
    details: ["Nationwide B8 LTE 5 MHz and B8 3G deployment"],
  },
];

export default data;
