var LTEBandData = {
    B1: {
        band: "B1",
        name: "IMT",
        frequency: 2100,
        duplexMode: "FDD",
        downlinkStartFrequency: 1920,
        downlinkEndFrequency: 1980,
        uplinkStartFrequency: 2110,
        uplinkEndFrequency: 2170,
    },
    B2: {
        band: "B2",
        name: "PCS",
        frequency: 1900,
        duplexMode: "FDD",
        downlinkStartFrequency: 1850,
        downlinkEndFrequency: 1910,
        uplinkStartFrequency: 1930,
        uplinkEndFrequency: 1990,
    },
    B3: {
        band: "B3",
        name: "DCS",
        frequency: 1800,
        duplexMode: "FDD",
        downlinkStartFrequency: 1710,
        downlinkEndFrequency: 1785,
        uplinkStartFrequency: 1805,
        uplinkEndFrequency: 1880,
    },
    B4: {
        band: "B4",
        name: "AWS-1",
        frequency: 1700,
        duplexMode: "FDD",
        downlinkStartFrequency: 1710,
        downlinkEndFrequency: 1755,
        uplinkStartFrequency: 2110,
        uplinkEndFrequency: 2155,
    },
    B5: {
        band: "B5",
        name: "Cellular",
        frequency: 850,
        duplexMode: "FDD",
        downlinkStartFrequency: 824,
        downlinkEndFrequency: 849,
        uplinkStartFrequency: 869,
        uplinkEndFrequency: 894,
    },
    B7: {
        band: "B7",
        name: "IMT-E",
        frequency: 2600,
        duplexMode: "FDD",
        downlinkStartFrequency: 2500,
        downlinkEndFrequency: 2570,
        uplinkStartFrequency: 2620,
        uplinkEndFrequency: 2690,
    },
    B8: {
        band: "B8",
        name: "GSM",
        frequency: 900,
        duplexMode: "FDD",
        downlinkStartFrequency: 880,
        downlinkEndFrequency: 915,
        uplinkStartFrequency: 925,
        uplinkEndFrequency: 960,
    },
    B11: {
        band: "B11",
        name: "Lower PDC (Japan)",
        frequency: 1500,
        duplexMode: "FDD",
        downlinkStartFrequency: 1427.9,
        downlinkEndFrequency: 1447.9,
        uplinkStartFrequency: 1475.9,
        uplinkEndFrequency: 1495.9,
    },
    B12: {
        band: "B12",
        name: "Lower SMH",
        frequency: 700,
        duplexMode: "FDD",
        downlinkStartFrequency: 699,
        downlinkEndFrequency: 716,
        uplinkStartFrequency: 729,
        uplinkEndFrequency: 746,
    },
    B13: {
        band: "B13",
        name: "Upper SMH",
        frequency: 700,
        duplexMode: "FDD",
        downlinkStartFrequency: 777,
        downlinkEndFrequency: 787,
        uplinkStartFrequency: 746,
        uplinkEndFrequency: 756,
    },
    B14: {
        band: "B14",
        name: "Upper SMH",
        frequency: 700,
        duplexMode: "FDD",
        downlinkStartFrequency: 788,
        downlinkEndFrequency: 798,
        uplinkStartFrequency: 758,
        uplinkEndFrequency: 768,
    },
    B17: {
        band: "B17",
        name: "Lower SMH",
        frequency: 700,
        duplexMode: "FDD",
        downlinkStartFrequency: 704,
        downlinkEndFrequency: 716,
        uplinkStartFrequency: 734,
        uplinkEndFrequency: 746,
    },
    B18: {
        band: "B18",
        name: "Lower 800 (Japan)",
        frequency: 850,
        duplexMode: "FDD",
        downlinkStartFrequency: 815,
        downlinkEndFrequency: 830,
        uplinkStartFrequency: 860,
        uplinkEndFrequency: 875,
    },
    B19: {
        band: "B19",
        name: "Upper 800 (Japan)",
        frequency: 850,
        duplexMode: "FDD",
        downlinkStartFrequency: 830,
        downlinkEndFrequency: 845,
        uplinkStartFrequency: 875,
        uplinkEndFrequency: 890,
    },
    B20: {
        band: "B20",
        name: "EU Digital Dividend",
        frequency: 800,
        duplexMode: "FDD",
        downlinkStartFrequency: 832,
        downlinkEndFrequency: 862,
        uplinkStartFrequency: 791,
        uplinkEndFrequency: 821,
    },
    B21: {
        band: "B21",
        name: "Upper PDC (Japan)",
        frequency: 1500,
        duplexMode: "FDD",
        downlinkStartFrequency: 1447.9,
        downlinkEndFrequency: 1462.9,
        uplinkStartFrequency: 1495.9,
        uplinkEndFrequency: 1510.9,
    },
    B24: {
        band: "B24",
        name: "Upper L-Band (USA)",
        frequency: 1600,
        duplexMode: "FDD",
        downlinkStartFrequency: 1626.5,
        downlinkEndFrequency: 1660.5,
        uplinkStartFrequency: 1525,
        uplinkEndFrequency: 1559,
    },
    B25: {
        band: "B25",
        name: "Extended PCS",
        frequency: 1900,
        duplexMode: "FDD",
        downlinkStartFrequency: 1850,
        downlinkEndFrequency: 1915,
        uplinkStartFrequency: 1930,
        uplinkEndFrequency: 1995,
    },
    B26: {
        band: "B26",
        name: "Extended Cellular",
        frequency: 850,
        duplexMode: "FDD",
        downlinkStartFrequency: 814,
        downlinkEndFrequency: 849,
        uplinkStartFrequency: 859,
        uplinkEndFrequency: 894,
    },
    B28: {
        band: "B28",
        name: "APT",
        frequency: 700,
        duplexMode: "FDD",
        downlinkStartFrequency: 703,
        downlinkEndFrequency: 748,
        uplinkStartFrequency: 758,
        uplinkEndFrequency: 803,
    },
    B29: {
        band: "B29",
        name: "Lower SMH SDL",
        frequency: 700,
        duplexMode: "SDL",
        startFrequency: 717,
        endFrequency: 728,
    },
    B30: {
        band: "B30",
        name: "WCS",
        frequency: 2300,
        duplexMode: "FDD",
        downlinkStartFrequency: 2305,
        downlinkEndFrequency: 2315,
        uplinkStartFrequency: 2350,
        uplinkEndFrequency: 2360,
    },
    B31: {
        band: "B31",
        name: "NMT",
        frequency: 450,
        duplexMode: "FDD",
        downlinkStartFrequency: 452.5,
        downlinkEndFrequency: 457.5,
        uplinkStartFrequency: 462.5,
        uplinkEndFrequency: 467.5,
    },
    B32: {
        band: "B32",
        name: "L-Band SDL (EU)",
        frequency: 1500,
        duplexMode: "SDL",
        startFrequency: 1452,
        endFrequency: 1496,
    },
    B34: {
        band: "B34",
        name: "IMT",
        frequency: 2000,
        duplexMode: "TDD",
        startFrequency: 2010,
        endFrequency: 2025,
    },
    B37: {
        band: "B37",
        name: "PCS",
        frequency: 1900,
        duplexMode: "TDD",
        startFrequency: 1910,
        endFrequency: 1930,
    },
    B38: {
        band: "B38",
        name: "IMT-E",
        frequency: 2600,
        duplexMode: "TDD",
        startFrequency: 2570,
        endFrequency: 2620,
    },
    B39: {
        band: "B39",
        name: "DCS-IMT Gap",
        frequency: 1900,
        duplexMode: "TDD",
        startFrequency: 1880,
        endFrequency: 1920,
    },
    B40: {
        band: "B40",
        name: "S-Band",
        frequency: 2300,
        duplexMode: "TDD",
        startFrequency: 2300,
        endFrequency: 2400,
    },
    B41: {
        band: "B41",
        name: "BRS (USA)",
        frequency: 2500,
        duplexMode: "TDD",
        startFrequency: 2496,
        endFrequency: 2690,
    },
    B42: {
        band: "B42",
        name: "CBRS (EU and Japan)",
        frequency: 3500,
        duplexMode: "TDD",
        startFrequency: 3400,
        endFrequency: 3600,
    },
    B43: {
        band: "B43",
        name: "C-Band",
        frequency: 3700,
        duplexMode: "TDD",
        startFrequency: 3600,
        endFrequency: 3800,
    },
    B46: {
        band: "B46",
        name: "LAA (U-NII-1 to 4)",
        frequency: 5200,
        duplexMode: "TDD",
        startFrequency: 5150,
        endFrequency: 5925,
    },
    B47: {
        band: "B47",
        name: "LAA (U-NII-4)",
        frequency: 5900,
        duplexMode: "TDD",
        startFrequency: 5855,
        endFrequency: 5925,
    },
    B48: {
        band: "B48",
        name: "CBRS (USA)",
        frequency: 3500,
        duplexMode: "TDD",
        startFrequency: 3550,
        endFrequency: 3700,
    },
    B50: {
        band: "B50",
        name: "L-band (EU)",
        frequency: 1500,
        duplexMode: "TDD",
        startFrequency: 1432,
        endFrequency: 1517,
    },
    B51: {
        band: "B51",
        name: "L-band Extension (EU)",
        frequency: 1500,
        duplexMode: "TDD",
        startFrequency: 1427,
        endFrequency: 1432,
    },
    B53: {
        band: "B53",
        name: "S-Band",
        frequency: 2400,
        duplexMode: "TDD",
        startFrequency: 2483.5,
        endFrequency: 2495,
    },
    B65: {
        band: "B65",
        name: "Extended IMT",
        frequency: 2100,
        duplexMode: "FDD",
        downlinkStartFrequency: 1920,
        downlinkEndFrequency: 2010,
        uplinkStartFrequency: 2110,
        uplinkEndFrequency: 2200,
    },
    B66: {
        band: "B66",
        name: "Extended AWS (AWS-1 to 3)",
        frequency: 1700,
        duplexMode: "FDD",
        downlinkStartFrequency: 1710,
        downlinkEndFrequency: 1780,
        uplinkStartFrequency: 2110,
        uplinkEndFrequency: 2200,
    },
    B67: {
        band: "B67",
        name: "700 MHz EU SDL",
        frequency: 700,
        duplexMode: "SDL",
        startFrequency: 738,
        endFrequency: 758,
    },
    B69: {
        band: "B69",
        name: "IMT-E SDL",
        frequency: 2600,
        duplexMode: "SDL",
        startFrequency: 2570,
        endFrequency: 2620,
    },
    B70: {
        band: "B70",
        name: "Supplementary AWS (AWS-2 to 4)",
        frequency: 1700,
        duplexMode: "FDD",
        downlinkStartFrequency: 1695,
        downlinkEndFrequency: 1710,
        uplinkStartFrequency: 1995,
        uplinkEndFrequency: 2020,
    },
    B71: {
        band: "B71",
        name: "USA Digital Dividend",
        frequency: 600,
        duplexMode: "FDD",
        downlinkStartFrequency: 663,
        downlinkEndFrequency: 698,
        uplinkStartFrequency: 617,
        uplinkEndFrequency: 652,
    },
    B72: {
        band: "B72",
        name: "EU PMR 450",
        frequency: 450,
        duplexMode: "FDD",
        downlinkStartFrequency: 451,
        downlinkEndFrequency: 456,
        uplinkStartFrequency: 461,
        uplinkEndFrequency: 466,
    },
    B73: {
        band: "B73",
        name: "APT PMR 450",
        frequency: 450,
        duplexMode: "FDD",
        downlinkStartFrequency: 450,
        downlinkEndFrequency: 455,
        uplinkStartFrequency: 460,
        uplinkEndFrequency: 465,
    },
    B74: {
        band: "B74",
        name: "Lower L-Band (USA)",
        frequency: 1500,
        duplexMode: "FDD",
        downlinkStartFrequency: 1427,
        downlinkEndFrequency: 1470,
        uplinkStartFrequency: 1475,
        uplinkEndFrequency: 1518,
    },
    B75: {
        band: "B75",
        name: "L-Band SDL (EU)",
        frequency: 1500,
        duplexMode: "SDL",
        startFrequency: 1432,
        endFrequency: 1517,
    },
    B76: {
        band: "B76",
        name: "L-Band SDL Extension (EU)",
        frequency: 1500,
        duplexMode: "SDL",
        startFrequency: 1427,
        endFrequency: 1432,
    },
    B85: {
        band: "B85",
        name: "Extended Lower SMH",
        frequency: 700,
        duplexMode: "FDD",
        downlinkStartFrequency: 698,
        downlinkEndFrequency: 716,
        uplinkStartFrequency: 728,
        uplinkEndFrequency: 746,
    },
    B87: {
        band: "B87",
        name: "APT PMR 410",
        frequency: 410,
        duplexMode: "FDD",
        downlinkStartFrequency: 410,
        downlinkEndFrequency: 415,
        uplinkStartFrequency: 420,
        uplinkEndFrequency: 425,
    },
    B88: {
        band: "B88",
        name: "EU PMR 410",
        frequency: 410,
        duplexMode: "FDD",
        downlinkStartFrequency: 412,
        downlinkEndFrequency: 417,
        uplinkStartFrequency: 422,
        uplinkEndFrequency: 427,
    },
    B103: {
        band: "B103",
        name: "Upper SMH",
        frequency: 700,
        duplexMode: "FDD",
        downlinkStartFrequency: 787,
        downlinkEndFrequency: 788,
        uplinkStartFrequency: 757,
        uplinkEndFrequency: 758,
    },
};
export { LTEBandData };
//# sourceMappingURL=LTEBandData.js.map